// Dota 2 英雄数据映射
// hero_id -> { name: 英文名(用于API/视频URL), localizedName: 英文显示名, cnName: 中文名 }
const HERO_DATA = {
    1: { name: "antimage", localizedName: "Anti-Mage", cnName: "敌法师" },
    2: { name: "axe", localizedName: "Axe", cnName: "斧王" },
    3: { name: "bane", localizedName: "Bane", cnName: "祸乱之源" },
    4: { name: "bloodseeker", localizedName: "Bloodseeker", cnName: "血魔" },
    5: { name: "crystal_maiden", localizedName: "Crystal Maiden", cnName: "水晶室女" },
    6: { name: "drow_ranger", localizedName: "Drow Ranger", cnName: "卓尔游侠" },
    7: { name: "earthshaker", localizedName: "Earthshaker", cnName: "撼地者" },
    8: { name: "juggernaut", localizedName: "Juggernaut", cnName: "主宰" },
    9: { name: "mirana", localizedName: "Mirana", cnName: "米拉娜" },
    10: { name: "morphling", localizedName: "Morphling", cnName: "变体精灵" },
    11: { name: "nevermore", localizedName: "Shadow Fiend", cnName: "影魔" },
    12: { name: "phantom_lancer", localizedName: "Phantom Lancer", cnName: "幻影长矛手" },
    13: { name: "puck", localizedName: "Puck", cnName: "帕克" },
    14: { name: "pudge", localizedName: "Pudge", cnName: "帕吉" },
    15: { name: "razor", localizedName: "Razor", cnName: "剃刀" },
    16: { name: "sand_king", localizedName: "Sand King", cnName: "沙王" },
    17: { name: "storm_spirit", localizedName: "Storm Spirit", cnName: "风暴之灵" },
    18: { name: "sven", localizedName: "Sven", cnName: "斯温" },
    19: { name: "tiny", localizedName: "Tiny", cnName: "小小" },
    20: { name: "vengefulspirit", localizedName: "Vengeful Spirit", cnName: "复仇之魂" },
    21: { name: "windrunner", localizedName: "Windranger", cnName: "风行者" },
    22: { name: "zuus", localizedName: "Zeus", cnName: "宙斯" },
    23: { name: "kunkka", localizedName: "Kunkka", cnName: "昆卡" },
    25: { name: "lina", localizedName: "Lina", cnName: "莉娜" },
    26: { name: "lion", localizedName: "Lion", cnName: "莱恩" },
    27: { name: "shadow_shaman", localizedName: "Shadow Shaman", cnName: "暗影萨满" },
    28: { name: "slardar", localizedName: "Slardar", cnName: "斯拉达" },
    29: { name: "tidehunter", localizedName: "Tidehunter", cnName: "潮汐猎人" },
    30: { name: "witch_doctor", localizedName: "Witch Doctor", cnName: "巫医" },
    31: { name: "lich", localizedName: "Lich", cnName: "巫妖" },
    32: { name: "riki", localizedName: "Riki", cnName: "力丸" },
    33: { name: "enigma", localizedName: "Enigma", cnName: "谜团" },
    34: { name: "tinker", localizedName: "Tinker", cnName: "修补匠" },
    35: { name: "sniper", localizedName: "Sniper", cnName: "狙击手" },
    36: { name: "necrolyte", localizedName: "Necrophos", cnName: "瘟疫法师" },
    37: { name: "warlock", localizedName: "Warlock", cnName: "术士" },
    38: { name: "beastmaster", localizedName: "Beastmaster", cnName: "兽王" },
    39: { name: "queenofpain", localizedName: "Queen of Pain", cnName: "痛苦女王" },
    40: { name: "venomancer", localizedName: "Venomancer", cnName: "剧毒术士" },
    41: { name: "faceless_void", localizedName: "Faceless Void", cnName: "虚空假面" },
    42: { name: "skeleton_king", localizedName: "Wraith King", cnName: "冥魂大帝" },
    43: { name: "death_prophet", localizedName: "Death Prophet", cnName: "死亡先知" },
    44: { name: "phantom_assassin", localizedName: "Phantom Assassin", cnName: "幻影刺客" },
    45: { name: "pugna", localizedName: "Pugna", cnName: "帕格纳" },
    46: { name: "templar_assassin", localizedName: "Templar Assassin", cnName: "圣堂刺客" },
    47: { name: "viper", localizedName: "Viper", cnName: "冥界亚龙" },
    48: { name: "luna", localizedName: "Luna", cnName: "露娜" },
    49: { name: "dragon_knight", localizedName: "Dragon Knight", cnName: "龙骑士" },
    50: { name: "dazzle", localizedName: "Dazzle", cnName: "戴泽" },
    51: { name: "rattletrap", localizedName: "Clockwerk", cnName: "发条技师" },
    52: { name: "leshrac", localizedName: "Leshrac", cnName: "拉席克" },
    53: { name: "furion", localizedName: "Nature's Prophet", cnName: "先知" },
    54: { name: "life_stealer", localizedName: "Lifestealer", cnName: "噬魂鬼" },
    55: { name: "dark_seer", localizedName: "Dark Seer", cnName: "黑暗贤者" },
    56: { name: "clinkz", localizedName: "Clinkz", cnName: "克林克兹" },
    57: { name: "omniknight", localizedName: "Omniknight", cnName: "全能骑士" },
    58: { name: "enchantress", localizedName: "Enchantress", cnName: "魅惑魔女" },
    59: { name: "huskar", localizedName: "Huskar", cnName: "哈斯卡" },
    60: { name: "night_stalker", localizedName: "Night Stalker", cnName: "暗夜魔王" },
    61: { name: "broodmother", localizedName: "Broodmother", cnName: "育母蜘蛛" },
    62: { name: "bounty_hunter", localizedName: "Bounty Hunter", cnName: "赏金猎人" },
    63: { name: "weaver", localizedName: "Weaver", cnName: "编织者" },
    64: { name: "jakiro", localizedName: "Jakiro", cnName: "杰奇洛" },
    65: { name: "batrider", localizedName: "Batrider", cnName: "蝙蝠骑士" },
    66: { name: "chen", localizedName: "Chen", cnName: "陈" },
    67: { name: "spectre", localizedName: "Spectre", cnName: "幽鬼" },
    68: { name: "ancient_apparition", localizedName: "Ancient Apparition", cnName: "远古冰魄" },
    69: { name: "doom_bringer", localizedName: "Doom", cnName: "末日使者" },
    70: { name: "ursa", localizedName: "Ursa", cnName: "熊战士" },
    71: { name: "spirit_breaker", localizedName: "Spirit Breaker", cnName: "裂魂人" },
    72: { name: "gyrocopter", localizedName: "Gyrocopter", cnName: "矮人直升机" },
    73: { name: "alchemist", localizedName: "Alchemist", cnName: "炼金术士" },
    74: { name: "invoker", localizedName: "Invoker", cnName: "祈求者" },
    75: { name: "silencer", localizedName: "Silencer", cnName: "沉默术士" },
    76: { name: "obsidian_destroyer", localizedName: "Outworld Destroyer", cnName: "殁境神蚀者" },
    77: { name: "lycan", localizedName: "Lycan", cnName: "狼人" },
    78: { name: "brewmaster", localizedName: "Brewmaster", cnName: "酒仙" },
    79: { name: "shadow_demon", localizedName: "Shadow Demon", cnName: "暗影恶魔" },
    80: { name: "lone_druid", localizedName: "Lone Druid", cnName: "德鲁伊" },
    81: { name: "chaos_knight", localizedName: "Chaos Knight", cnName: "混沌骑士" },
    82: { name: "meepo", localizedName: "Meepo", cnName: "米波" },
    83: { name: "treant", localizedName: "Treant Protector", cnName: "树精卫士" },
    84: { name: "ogre_magi", localizedName: "Ogre Magi", cnName: "食人魔魔法师" },
    85: { name: "undying", localizedName: "Undying", cnName: "不朽尸王" },
    86: { name: "rubick", localizedName: "Rubick", cnName: "拉比克" },
    87: { name: "disruptor", localizedName: "Disruptor", cnName: "干扰者" },
    88: { name: "nyx_assassin", localizedName: "Nyx Assassin", cnName: "司夜刺客" },
    89: { name: "naga_siren", localizedName: "Naga Siren", cnName: "娜迦海妖" },
    90: { name: "keeper_of_the_light", localizedName: "Keeper of the Light", cnName: "光之守卫" },
    91: { name: "wisp", localizedName: "Io", cnName: "艾欧" },
    92: { name: "visage", localizedName: "Visage", cnName: "维萨吉" },
    93: { name: "slark", localizedName: "Slark", cnName: "斯拉克" },
    94: { name: "medusa", localizedName: "Medusa", cnName: "美杜莎" },
    95: { name: "troll_warlord", localizedName: "Troll Warlord", cnName: "巨魔战将" },
    96: { name: "centaur", localizedName: "Centaur Warrunner", cnName: "半人马战行者" },
    97: { name: "magnataur", localizedName: "Magnus", cnName: "马格纳斯" },
    98: { name: "shredder", localizedName: "Timbersaw", cnName: "伐木机" },
    99: { name: "bristleback", localizedName: "Bristleback", cnName: "钢背兽" },
    100: { name: "tusk", localizedName: "Tusk", cnName: "巨牙海民" },
    101: { name: "skywrath_mage", localizedName: "Skywrath Mage", cnName: "天怒法师" },
    102: { name: "abaddon", localizedName: "Abaddon", cnName: "亚巴顿" },
    103: { name: "elder_titan", localizedName: "Elder Titan", cnName: "上古巨神" },
    104: { name: "legion_commander", localizedName: "Legion Commander", cnName: "军团指挥官" },
    105: { name: "techies", localizedName: "Techies", cnName: "工程师" },
    106: { name: "ember_spirit", localizedName: "Ember Spirit", cnName: "灰烬之灵" },
    107: { name: "earth_spirit", localizedName: "Earth Spirit", cnName: "大地之灵" },
    108: { name: "abyssal_underlord", localizedName: "Underlord", cnName: "孽主" },
    109: { name: "terrorblade", localizedName: "Terrorblade", cnName: "恐怖利刃" },
    110: { name: "phoenix", localizedName: "Phoenix", cnName: "凤凰" },
    111: { name: "oracle", localizedName: "Oracle", cnName: "神谕者" },
    112: { name: "winter_wyvern", localizedName: "Winter Wyvern", cnName: "寒冬飞龙" },
    113: { name: "arc_warden", localizedName: "Arc Warden", cnName: "天穹守望者" },
    114: { name: "monkey_king", localizedName: "Monkey King", cnName: "齐天大圣" },
    119: { name: "dark_willow", localizedName: "Dark Willow", cnName: "邪影芳灵" },
    120: { name: "pangolier", localizedName: "Pangolier", cnName: "石鳞剑士" },
    121: { name: "grimstroke", localizedName: "Grimstroke", cnName: "天涯墨客" },
    123: { name: "hoodwink", localizedName: "Hoodwink", cnName: "森海飞霞" },
    126: { name: "void_spirit", localizedName: "Void Spirit", cnName: "虚无之灵" },
    128: { name: "snapfire", localizedName: "Snapfire", cnName: "电炎绝手" },
    129: { name: "mars", localizedName: "Mars", cnName: "玛尔斯" },
    131: { name: "ringmaster", localizedName: "Ringmaster", cnName: "马戏之王" },
    135: { name: "dawnbreaker", localizedName: "Dawnbreaker", cnName: "破晓辰星" },
    136: { name: "marci", localizedName: "Marci", cnName: "玛西" },
    137: { name: "primal_beast", localizedName: "Primal Beast", cnName: "远古恐惧" },
    138: { name: "muerta", localizedName: "Muerta", cnName: "琼英碧灵" },
    145: { name: "kez", localizedName: "Kez", cnName: "凯兹" },
    155: { name: "largo", localizedName: "Largo", cnName: "拉尔戈" }
};

// 游戏模式映射
const GAME_MODES = {
    0: "未知",
    1: "全英雄选择",
    2: "队长模式",
    3: "随机征召",
    4: "单选模式",
    5: "全英雄随机",
    11: "中路solo",
    12: "最少选择",
    13: "有限英雄",
    14: "队长征召",
    15: "人机对战",
    16: "死亡竞赛",
    18: "技能征召",
    19: "乱斗模式",
    22: "全英雄选择（排名）",
    23: "加速模式"
};

// 大厅类型映射
const LOBBY_TYPES = {
    0: "普通匹配",
    1: "练习赛",
    2: "锦标赛",
    4: "合作模式",
    5: "排名天梯",
    6: "亲信天梯",
    7: "排名匹配",
    8: "活动匹配",
    9: "混合匹配"
};

// 获取英雄视频URL
function getHeroVideoUrl(heroName) {
    return `https://cdn.akamai.steamstatic.com/apps/dota2/videos/dota_react/heroes/renders/${heroName}.webm`;
}

// 获取英雄头像URL
function getHeroIconUrl(heroName) {
    return `https://cdn.akamai.steamstatic.com/apps/dota2/images/dota_react/heroes/${heroName}.png`;
}

// 获取英雄大图URL
function getHeroFullUrl(heroName) {
    return `https://cdn.akamai.steamstatic.com/apps/dota2/images/dota_react/heroes/crops/${heroName}.png`;
}
